pipeline {
    agent { label 'Jenkins-Agent' }

    tools {
        maven 'Maven3'

    }

    environment {
	    APP_NAME = "petcare-backend"
        RELEASE = "1.0.0"
        DOCKER_USER = "zetnguyen17"
        DOCKER_PASS = 'dockerhub'
        IMAGE_NAME = "${DOCKER_USER}" + "/" + "${APP_NAME}"
        IMAGE_TAG = "${RELEASE}-${BUILD_NUMBER}"
	    JENKINS_API_TOKEN = credentials("JENKINS_API_TOKEN")
    }

    stages{
        stage("Cleanup Workspace"){
                steps {
                    cleanWs()
                }
        }
        stage("Checkout from SCM"){
                steps {
                    git branch: 'uat', credentialsId: 'github', url: 'https://github.com/HCMIU-Software-Engineering/Software-Engineering-Project'
                }
        }

        stage("Build Application & Test Application"){
            steps {
                dir("API/petcare"){
                    sh """
                        mvn clean install
                        mvn test
                    """    
                }
                
            }
        }


        stage("Build & Push Docker Image") {
                steps {
                    dir("API/petcare"){
                        script {
                            docker.withRegistry('',DOCKER_PASS) {
                                docker_image = docker.build "${IMAGE_NAME}"
                            }

                            docker.withRegistry('',DOCKER_PASS) {
                                docker_image.push("${IMAGE_TAG}")
                            }
                        }
                    }
                }

        }

        stage ('Cleanup Artifacts') {
            steps {
                dir("API/petcare"){
                    script {
                        sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG}"
                    }
                }
            }
        }
        stage("Trigger CD Pipeline") {
            steps {
                script {
                    sh "curl -v -k --user clouduser:${JENKINS_API_TOKEN} -X POST -H 'cache-control: no-cache' -H 'content-type: application/x-www-form-urlencoded' --data 'IMAGE_TAG=${IMAGE_TAG}' 'ec2-13-232-128-192.ap-south-1.compute.amazonaws.com:8080/job/gitops-register-app-cd/buildWithParameters?token=gitops-token'"
                }
            }
       }
    }



}
