pipeline {
    agent { label 'Jenkins-Agent' }

    tools {
        maven 'Maven3'

    }

    environment {
	    APP_NAME = "petcare-backend"
        RELEASE = "1.0.0"
        DOCKER_USER = "zetnguyen17"
        DOCKER_PASS = 'dockerhub'
        IMAGE_NAME = "${DOCKER_USER}" + "/" + "${APP_NAME}"
        IMAGE_TAG = "${RELEASE}-${BUILD_NUMBER}"
	    //JENKINS_API_TOKEN = credentials("JENKINS_API_TOKEN")
    }

    stages{
        stage("Cleanup Workspace"){
                steps {
                    cleanWs()
                }
        }
        stage("Checkout from SCM"){
                steps {
                    git branch: 'uat', credentialsId: 'github', url: 'https://github.com/HCMIU-Software-Engineering/Software-Engineering-Project'
                }
        }

        stage("Build Application & Test Application"){
            steps {
                dir("API/petcare"){
                    sh """
                        mvn clean install
                        mvn test
                    """    
                }
                
            }

       }


        stage("Build & Push Docker Image") {
                steps {
                    script {
                        docker.withRegistry('',DOCKER_PASS) {
                            docker_image = docker.build "${IMAGE_NAME}"
                        }

                        docker.withRegistry('',DOCKER_PASS) {
                            docker_image.push("${IMAGE_TAG}")
                            docker_image.push('latest')
                        }
                    }
                }

        }

        stage ('Cleanup Artifacts') {
            steps {
                script {
                    sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG}"
                    sh "docker rmi ${IMAGE_NAME}:latest"
                }
            }
        }
    }



}
