pipeline {
    agent { label 'Jenkins-Agent' }

    tools {
        maven 'Maven3'

    }

    environment {
	    APP_NAME = "petcare-frontend"
        RELEASE = "1.0.0"
        DOCKER_USER = "zetnguyen17"
        DOCKER_PASS = 'dockerhub'
        IMAGE_NAME = "${DOCKER_USER}" + "/" + "${APP_NAME}"
        IMAGE_TAG = "${RELEASE}-${BUILD_NUMBER}"
	    JENKINS_API_TOKEN = credentials("JENKINS_API_TOKEN")
    }

    stages{
        stage("Cleanup Workspace"){
            steps {
                cleanWs()
            }
        }


        stage("Build & Push Docker Image") {
                steps {
                    dir("petcareapp"){
                        script {
                            docker.withRegistry('',DOCKER_PASS) {
                                docker_image = docker.build "${IMAGE_NAME}"
                            }

                            docker.withRegistry('',DOCKER_PASS) {
                                docker_image.push("${IMAGE_TAG}")
                            }
                        }
                    }
                }

        }

        stage ('Cleanup Artifacts') {
            steps {
                script {
                    sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }
        stage("Trigger CD Pipeline") {
            steps {
                script {
                    sh "curl -v -k --user admin:${JENKINS_API_TOKEN} -X POST -H 'cache-control: no-cache' -H 'content-type: application/x-www-form-urlencoded' --data 'IMAGE_TAG=${IMAGE_TAG}' 'http://13.212.77.45:8080/job/gitops-UI/buildWithParameters?token=gitops-token'"
                }
            }
        }
    }



}
